// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzluxjpvulnszqzsckit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6bHV4anB2dWxuc3pxenNja2l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDM0OTYsImV4cCI6MjA2MTE3OTQ5Nn0.MkwWSqttpPuRWFXG_jNev1XYMgrlaIUkjkwOaBuG48U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);