// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjvzmxlulcaydkeaazsol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2em16bHVsY2F5ZGtlYXpyc29sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NDk0ODIsImV4cCI6MjA2MjIyNTQ4Mn0.HNlswWyXuA4nw1MsR4E_6N8JKoq7Ntc5bV09NS5r0j8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
